version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: fretappDB
    restart: unless-stopped
    environment:
    - POSTGRES_DB=fretappdb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgresPass
    ports:
    - '5432:5432'
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
  app:
    build: .
    container_name: fretapp
    command: >
      bash -c "sleep 15 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    volumes:
    - .:/app
    ports:
    - "8000:8000"
    depends_on:
    - postgres

volumes:
  postgres-data: