# Generated by Django 4.0.3 on 2022-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('doc', models.CharField(max_length=18)),
                ('about', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('site', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('doc', models.CharField(max_length=18)),
                ('about', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('site', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
