# Generated by Django 4.0.3 on 2022-04-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empesa',
            new_name='Empresa',
        ),
    ]
