# Generated by Django 4.0.3 on 2022-04-05 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_address', models.CharField(max_length=64)),
                ('to_address', models.CharField(max_length=64)),
                ('initial_value', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('amount_type', models.CharField(max_length=16)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.customer')),
            ],
        ),
    ]
