# Generated by Django 4.0.3 on 2022-04-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='from_address',
            new_name='_from',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='to_address',
            new_name='to',
        ),
    ]
