# Generated by Django 4.0.3 on 2022-04-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busyness', '0002_rename_from_address_offer__from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='_from',
            new_name='From',
        ),
    ]
