# Generated by Django 4.0.3 on 2022-04-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_alter_customer_doc_alter_customer_name_and_more'),
        ('busyness', '0003_rename__from_offer_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('id_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='busyness.offer')),
                ('id_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enterprises.provider')),
            ],
        ),
    ]
